### ISSUE TITLE
Importing from '.' does not work

### ISSUE THREAD

**Issue by laverdet** [K-FOSS/TS-ESNode#34]
`index.ts`
```ts
export function log() {
	console.log(1);
}
```

`hello.ts`
```ts
import { log } from '.';
log();
```

Run command: `node --loader '@k-foss/ts-esnode' --experimental-specifier-resolution=node ./hello.ts`

Error: Cannot find module /Users/marcel/ imported from /Users/marcel/hello.ts

**Comment by KristianFJones** [comment]
Can you install `npm i @k-foss/ts-esnode@next` and try again. I think a fix I have in testing right now may fix your issue. Please report here if it works or not.

**Comment by laverdet** [comment]
It seems like the case still fails on the `next` branch:

```
marcel@marcel ~/code/TS-ESNode/tmp $ git rev-parse HEAD
bf5d885fe0c91550fe0599c92672dbf9bed477df

marcel@marcel ~/code/TS-ESNode/tmp $ npm run build
> @k-foss/ts-esnode@1.3.5 prebuild /Users/marcel/code/TS-ESNode
> tsc -p ./bin/
[...]

marcel@marcel ~/code/TS-ESNode/tmp $ node --loader '../out/dist/index.js' --experimental-specifier-resolution=node ./hello.ts
(node:860) ExperimentalWarning: The ESM module loader is experimental.
(node:860) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
internal/modules/esm/resolve.js:58
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /Users/marcel/code/TS-ESNode/tmp/ imported from /Users/marcel/code/TS-ESNode/tmp/hello.ts
    at defaultResolve (internal/modules/esm/resolve.js:58:13)
    at resolve (file:///Users/marcel/code/TS-ESNode/out/dist/index.js:42:12)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:188:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

marcel@marcel ~/code/TS-ESNode/tmp $ l
-rw-r--r--  1 marcel  staff    32B Apr  8 14:50 hello.ts
-rw-r--r--  1 marcel  staff    43B Apr  8 14:50 index.ts
```

**Comment by KristianFJones** [comment]
This should be fixed now.
