### ISSUE TITLE
Axios: "SyntaxError: Identifier '$default' has already been declared"

### ISSUE THREAD

**Issue by staeke** [K-FOSS/TS-ESNode#9]
The code below fails with error:

```
file://.../node_modules/axios/index.js:117
let $default;
    ^

SyntaxError: Identifier '$default' has already been declared
    at createDynamicModule (internal/modules/esm/create_dynamic_module.js:37:13)
    at Loader.loaderInstance (internal/modules/esm/loader.js:204:16)
    at async link (internal/modules/esm/module_job.js:37:21)
```

Commannd:

```bash
node --loader @k-foss/ts-esnode --experimental-specifier-resolution=node src/index.ts
```

```ts
// src/index.ts
import axios from "axios";
console.log(axios);
```

tsconfig:

```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "lib": [
      "esnext"
    ],
    "target": "esnext",
    "module": "esnext"
  }
}
```

**Comment by staeke** [comment]
PR here https://github.com/K-FOSS/TS-ESNode/pull/10
